### ISSUE TITLE
Request body is not present in the RaygunRequestMessage

### ISSUE THREAD

**Issue by wichon** [phillip-haydon/Nancy.Raygun#7]
After checking the code, that part is commented is there a reason for that?

Regards.
Luis

Great work btw :)

**Comment by phillip-haydon** [comment]
Yeah there's weird cases where getting the body can cause the exception to not be sent to Raygun. 

I was waiting for a whole heap of new changes to happen in the official raygun project so I can migrate it to Nancy.Raygun, but I completely forgot about it. 

Im slowly working on some changes but if you want to help out that would be awesome :)

**Comment by wichon** [comment]
Yeah sure, let know what do you need and i can work on that.

**Comment by wichon** [comment]
Hey men, i found the issue, when trying to convert the Body that is a RequestStream object to a Dictionary the ToDictionary method failed and simply didn't continue with sending the event to raygun, so i did a little change and instead of converting it to a Dictionary, i converted it to a string and leave it like that, so when you get the error report in the raygun dashboard you will get the exact Body that the application got in the request, i am creating a pull request if you want to integrate it with your project.

Regards.

**Comment by phillip-haydon** [comment]
Would love a PR! If you can get it in the next day I can publish some new nugets. Otherwise I'm going to be away from Friday till Monday next week.

**Comment by phillip-haydon** [comment]
Closed with #8 
https://www.nuget.org/packages/Nancy.Raygun/

New package live. Lemme know if there's any issues. 

Thanks a lot!

**Comment by wichon** [comment]
Awesome!, is working now thanks men! :D

**Comment by wichon** [comment]
In case someone is still getting an empty body in the raygun dashboard, when nancy binds the body to an object it moves the cursor to the end, and it is because the body in the nancy request object is an stream so when it is binded the stream is readed to the end and the cursor stays at the end of the stream son any subsequent read to the body will return an empty string. To fix this just return the cursor to the beginning of the stream with: this.Request.Body.Position = 0; just after binding the object. That will let Nancy.Raygun to access the body when reporting an error.
